version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    # Linux: you can use any hostname instead of "host.docker.internal"
    # MacOS: you have to use "host.docker.internal" because it resolves to host IP
    command: -f /mnt/locust/locustfile.py --master -H http://myhost:8000 --expect-workers 4 --headless

  worker:
    image: locustio/locust
    # Linux: you have to use extra_hosts to put myhost:<HOST IP> record to /etc/hosts
    # MacOS: you don't need extra_hosts section
    extra_hosts:
      - "myhost:host-gateway"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master